### ISSUE TITLE
Breaking change: `p-text-truncate` is missing from PrimeFlex 3

### ISSUE THREAD

**Issue by Wandmalfarbe** [primefaces/primeflex#73]
When migrating one of my projects from PrimeFlex 2 to PrimeFlex 3 I noticed that the class `p-text-truncate` is missing in PrimeFlex 3. There is currently no way to truncate text with the new PrimeFlex.

```css
.p-text-truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

The migration guide doesn't mention this breaking change either (https://www.primefaces.org/primeflex/migration).
