### ISSUE TITLE
Adding vertical-align support

### ISSUE THREAD

**Issue by commodis** [primefaces/primeflex#92]
> The `vertical-align` CSS property sets vertical alignment of an inline, inline-block or table-cell box.

https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align

I searched through primeflex and found [no support](https://github.com/primefaces/primeflex/search?q=vertical-align) for `vertical-align` but there is support for a CSS property which is used in a similar fashion: [`text-align`](https://www.primefaces.org/primeflex/textalign)

Following the example of `text-align` a possible resolution could look like this:

```css
.vertical-baseline {
    vertical-align: baseline !important;
}

.vertical-sub {
    vertical-align: sub !important;
}

.vertical-super {
    vertical-align: super !important;
}

.vertical-text-top {
    vertical-align: text-top !important;
}

.vertical-text-bottom {
    vertical-align: text-top !important;
}

.vertical-top {
    vertical-align: top !important;
}

.vertical-middle {
    vertical-align: middle !important;
}

.vertical-bottom {
    vertical-align: bottom !important;
}
```

Technically there is also support for percentage and length which could be handled like https://www.primefaces.org/primeflex/padding but in my experience the usage of percentage and fixed-length are rarely used.
